language: node_js
os: linux
node_js: lts/*

jobs:
  include:
    - stage: test
      node_js: lts/*
      before_script: npm run lint
    - stage: test
      node_js: node

    # Check the commit messages
    - stage: test
      script:
        - commitlint-travis

    - stage: release
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

dist: trusty

sudo: false

stages:
  - test
  - name: release
    if: (NOT type = pull_request) AND branch = master
