language: node_js
os: linux

jobs:
  include:
    - stage: test
      node_js: lts/*
    - stage: test
      node_js: node

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - "/^greenkeeper/.*$/"

git:
  depth: 10

dist: trusty

sudo: false

stages:
  - test
